services:
  db:
    image: postgres:15-alpine
    container_name: pharma-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: pharma
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
